config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :calls

  root 'calls#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/call.rb
class Call < ApplicationRecord
  TWILIO_SID = 'AC374132137e4aaf739389321cdf60c670'
  AUTH_TOKEN = 'AC374132137e4aaf739389321cdf60c670'
  CALL_NUM = '+1 855 925 3672'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calls_controller.rb
class CallsController < ApplicationController
  def new
    @call = Call.new
  end

  def create
    @client = Twilio::REST::Client.new(Call::TWILIO_SID, Call::AUTH_TOKEN)
    @call = Call.new(call_params)
    if @call.save
      call = @client.calls.create(
                                  twiml: '<Response><Say>Ahoy, World!</Say></Response>',
                                  to: '+91 '+params[:to_num],
                                  from: Call::CALL_NUM
                                  )
    end
  end

  private

  def call_params
    params.require(:call).permit(:name, :call_to, :to_num)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calls_helper.rb
module CallsHelper
end

app/views/calls/index.html.erb
<%= link_to 'Make New Call', new_call_path %>

app/views/calls/new.html.erb
<%= form_for(@call, local: true) do |f| %>
  <%= f.label :name, 'Your Name' %>
  <%= f.text_field :name %>
  <%= f.label :call_to, 'Calling Person Name' %>
  <%= f.text_field :call_to %>
  <%= f.label :to_num, 'Mobile number to dial' %>
  <%= f.text_field :to_num %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwilioCall</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>